# $Rev$
TARGET = main
CC = gcc
CFLAGS = -Wall -Wextra -Wdeclaration-after-statement -Wbad-function-cast \
         -Wcast-qual -Wstrict-prototypes -Wmissing-declarations \
         -Wmissing-prototypes -Werror -g
LIBS = -lpthread -lm conc_queue.o task_queue.o thread_pool.o
SOURCES = $(shell echo *.c)
OBJECTS = $(SOURCES:%.c=%.o)

all: $(TARGET)

test: $(OBJECTS)
	make -C tests test

$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)

-include .depend

.depend: $(SOURCES) *.h
	$(CC) -MM $(SOURCES) > .depend

.PHONY: clean

clean:
	make -C tests clean
	rm -f $(TARGET) $(OBJECTS) .depend *~
